#!/usr/bin/env python3

import argparse
from pathlib import Path
import sys
import subprocess
import re


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "workspace",
        help="Path to ROS2 workspace",
    )
    parser.add_argument(
        "-p",
        "--package",
        help="bringup package name",
        required=True,
    )
    parser.add_argument(
        "-n",
        "--node",
        help="ROS2 node name (when used in 'run' mode), or launch script "
        + "name (when used in 'launch' mode)",
        required=True,
    )
    parser.add_argument(
        "-r",
        "--niceness",
        help="Niceness setting: an integer value in range [-20:19] where "
        + "-20 is the best performance (default=-20)",
        default=-20,
    )
    parser.add_argument(
        "-a",
        "--fcat-launch-arguments",
        help="Additional arguments to pass to fcat launch file"
        + "mode",
        default=None,
    )
    return parser.parse_args()


def sanitize(string):
    """prevent command injection by stripping off anything following a
    semicolon or comma"""
    if string is None:
        return ""
    else:
        return re.split(";|,", string)[0]


def run_command(command, cwd=Path.cwd()):
    cmd = ["/bin/bash", "-c"] + [command]
    try:
        p = subprocess.run(
            cmd, stdout=sys.stdout, stderr=sys.stderr, cwd=cwd, check=True
        )
        return p.returncode
    except KeyboardInterrupt:
        return 1
    except subprocess.CalledProcessError as e:
        print(f"Error: command '{command}' returned non-zero exit status")
        return e.returncode


def main():
    args = parse_args()

    # verify workspace exists
    if not Path(args.workspace).is_dir():
        print(f"Error: {args.workspace} is an invalid directory")
        sys.exit(-1)

    sys.exit(
        run_command(
            "source install/setup.bash && "
            + f"nice -n {args.niceness} "
            + f"ros2 launch {sanitize(args.package)} {sanitize(args.node)} "
            + f"{sanitize(args.fcat_launch_arguments)}",
            Path(args.workspace),
        )
    )


if __name__ == "__main__":
    main()
